trello2/config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	resources :tasks
	resources :cards
  get '/tasks/:id/check', to: 'tasks#check',  as: "check_task"

  get 'signup'  => 'users#new'
  resources :users


  get    'login'   => 'auth#new'
  post   'login'   => 'auth#create'
  delete 'logout'  => 'auth#destroy'
  root to: "home#index"

end

trello2/app/models/task.rb
class Task < ApplicationRecord

  validates :title,  presence: true, length: { maximum: 255 }
  validates :checked, numericality: { less_than_or_equal_to: 1,  only_integer: true, greater_than_or_equal_to: 0 }

  scope :user, -> (user_id) { where("user_id = ?", user_id) }

  def is_checked
    self.checked > 0
  end
end

trello2/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include AuthHelper
  before_action :logged_in_user

  def index
    redirect_to cards_path
  end

  def show
    @task = Task.find_by(id: params[:id], user_id: current_user.id)

    if @task.nil?
      redirect_to cards_path
    end

  end

  def new
    @task = Task.new
    @task.card_id = params[:id]

    @card = Card.find_by(id: @task.card_id)
  end

  def create
    @task = Task.new(task_params)
    @card = Card.find_by(id: @task.card_id, user_id: current_user.id)

    if @card.nil?
      flash[:danger] = 'Ошибка при сохранении'
      redirect_to cards_path
      return
    end

    @task.user_id = current_user.id
    if @task.save
      flash[:primary] = 'Задача добавлена'
      redirect_to cards_path
    else
      flash[:danger] = 'Ошибка при сохранении'
      render :new
    end
  end

  def edit
    @task = Task.find_by(id: params[:id], user_id: current_user.id)

    if @task.nil?
      redirect_to cards_path
    end
  end

  def update
    @task = Task.find_by(id: params[:id], user_id: current_user.id)
    if @task.nil?
      redirect_to cards_path
      return
    end

    if @task.update_attributes(task_params)
      flash[:primary] = 'Задача обновлена'
      redirect_to cards_path
    else
      flash[:danger] = 'Ошибка при сохранении'
      render :edit
    end
  end

  def check
    @task = Task.find_by(id: params[:id], user_id: current_user.id)
    if @task.nil?
      redirect_to cards_path
      return
    end

    task_params = { :checked => @task.is_checked ? 0 : 1 }

    if @task.update_attributes(task_params)
      flash[:primary] = 'Задача обновлена'
      redirect_to @task
    else
      flash[:danger] = 'Ошибка при сохранении'
      render :edit
    end
  end

  def destroy
    @task = Task.find_by(id: params[:id], user_id: current_user.id)
    if @task.nil?
      redirect_to cards_path
      return
    end

    if @task.destroy
      flash[:primary] = "Задача #{@task.title} удалена"
      redirect_to cards_path
    end
  end

  def task_params
    params.require(:task).permit(:title, :description, :card_id)
  end

end

trello2/app/helpers/tasks_helper.rb
module TasksHelper
end

trello2/app/views/tasks/edit.html.erb
<%= form_for @task, url: {action: :update} do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <ul>
          <% @task.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "Название" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Описание" %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Сохранить", class: "btn btn-primary" %>
  </div>
<% end %>

trello2/app/views/tasks/new.html.erb
<%= form_for @task, url: { action: :create } do |f| %>

  <% if @task.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <ul>
          <% @task.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :title, "Название" %>
    <%= f.text_field :title, class: 'form-control' %>
    <%= f.hidden_field :card_id, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Описание" %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Сохранить", class: "btn btn-primary" %>
  </div>
<% end %>

trello2/app/views/tasks/show.html.erb
<div class="row justify-content-center">
  <div class="col-md-7 col-12 ">
    <div>
      <%= link_to 'Назад', cards_path %>
    </div>
    <div class="card">
      <div class="card-body">
        <p>
          <%= link_to 'Редактировать', edit_task_path(id: @task.id), class: 'btn btn-primary' %>
          <%= link_to 'Удалить', task_path(id: @task.id), class: 'btn btn-danger', method:'delete' %>
          <%= link_to @task.is_checked ? 'Не выполнено' :  'Выполнено', check_task_url(id: @task.id), class: 'btn btn-warning', method:'get' %>
        </p>
        <h2><%= @task.title %></h2>
        <p><%= @task.description %></p>
      </div>
    </div>
  </div>
</div>