trello2/config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end

  post "/graphql", to: "graphql#execute"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	resources :tasks
	resources :cards
  get '/tasks/:id/check', to: 'tasks#check',  as: "check_task"

  get 'signup'  => 'users#new'
  resources :users


  get    'login'   => 'auth#new'
  post   'login'   => 'auth#create'
  delete 'logout'  => 'auth#destroy'
  root to: "home#index"

end

trello2/app/models/card.rb
class Card < ApplicationRecord
  include AuthHelper
  before_save { self.name = name.upcase; }
  validates :name, presence: true, length: { maximum: 255 }

  has_many :tasks, foreign_key: "card_id"
  scope :not_archive, -> { where("created_at > ?", 1.month.ago.to_i) }
  scope :archive, -> { where("created_at <= ?", 1.month.ago.to_i) }

  scope :user, -> (user_id) { where("user_id = ?", user_id) }
end

trello2/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  include AuthHelper
  before_action :logged_in_user

  def index
    if params[:archive]
      @cards = Card.archive.user(current_user.id).all
    else
      @cards = Card.not_archive.user(current_user.id).all
    end
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(card_params)
    @card.user_id = current_user.id
    if @card.save
      flash[:primary] = 'Карточка добавлена'
      redirect_to cards_path
    else
      flash[:danger] = 'Ошибка при сохранении карточки'
      render :new
    end
  end

  def edit
    @card = Card.find_by(id: params[:id], user_id: current_user.id)


    if @card.nil?
      redirect_to cards_path
    end
  end

  def update
    @card = Card.find_by(id: params[:id], user_id: current_user.id)


    if @card.nil?
      redirect_to cards_path
    end

    if @card.update_attributes(card_params)
      flash[:primary] = 'Карточка обновлена'
      redirect_to cards_path
    else
      flash[:danger] = 'Ошибка при сохранении карточки'
      render :edit
    end
  end

  def destroy
    @card = Card.find_by(id: params[:id], user_id: current_user.id)
    if @card.nil?
      redirect_to cards_path
    end
    if @card.destroy
      flash[:primary] = "Карточка #{@card.name} удалена"
      redirect_to cards_path
    end
  end

  def card_params
    params.require(:card).permit(:name)
  end
end

trello2/app/views/cards/edit.html.erb
<%= form_for @card, url: {action: :update} do |f| %>

  <% if @card.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <ul>
          <% @card.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="form-group">

    <%= f.label :name, "Название" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <div class="float-left">

      <%= f.submit "Сохранить", class: "btn btn-primary" %>
    </div>
    <div class="float-right">
      <%= link_to 'Удалить', card_path(id: @card.id), class:'btn btn-danger', method: :delete %>
    </div>
  </div>
<% end %>

trello2/app/views/cards/form.html.erb
<div class="form-group">
  <label for="title">Title</label>
  <input type="text" class="form-control" id="title" name="task[title]" value="<%= @task.title %>">
</div>
<div class="form-group">
  <label for="desc">Description</label>
  <textarea class="form-control" id="desc" name="task[description]"><%= @task.description %></textarea>
</div>
<div class="form-group">
  <input type="submit" class="btn btn-success" value="Save">
</div>

trello2/app/views/cards/index.html.erb
<div class="overflow-hidden mb-3">
  <div class="float-left">
    <%= link_to 'Добавить', new_card_path, class: 'btn btn-success' %>
  </div>
  <div class="float-right">
    <% if params[:archive] %>
      <%= link_to 'Показать все', cards_path, class: 'btn btn-success' %>
    <% else %>
      <%= link_to 'Показать архивные', cards_path(archive: 1), class: 'btn btn-warning' %>
    <% end %>
  </div>
</div>
<% if @cards.empty? %>
  <h3 class="text-primary text-center">Карточек нет. Добавьте новую</h3>
<% end %>
<div class="cards row">
  <% @cards.each do |card| %>
    <div class="col-md-4 col-sm-6 col-12">
      <div class="card">
        <div class="card-body">

          <div class="overflow-hidden">
            <div class="float-left h3">
              <%= card.name %>
            </div>

            <div class="float-right">
              <a href="<%= edit_card_path card %>"><i class="bi bi-pencil"></i></a>
            </div>
          </div>

          <% if card.tasks.empty? %>
            <span class="text-danger">Нет задач</span>
          <% end %>
          <% card.tasks.each do |task| %>
            <%= link_to task.title, task_path(task.id), class: 'card-task ' + (task.is_checked ? 'card-task-done' : '') %>
          <% end %>
          <div>
            <%= link_to 'Добавить задачу', new_task_path(id: card.id), class: 'btn btn-primary btn-sm' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

trello2/app/views/cards/new.html.erb
<%= form_for @card do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <ul>
          <% @card.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>


  <div class="form-group">

    <%= f.label :name, "Название" %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">

    <%= f.submit "Сохранить", class: "btn btn-primary" %>
  </div>
<% end %>